<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22118" started-at="2019-11-14T08:23:34Z" finished-at="2019-11-14T08:23:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22118" started-at="2019-11-14T08:23:34Z" finished-at="2019-11-14T08:23:56Z">
      <class name="com.edu.yanjie.LoginTest">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:com.edu.yanjie.LoginTest@27efef64]" name="doBeforeClass" is-config="true" duration-ms="7897" started-at="2019-11-14T08:23:34Z" finished-at="2019-11-14T08:23:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="FAIL" signature="loginFail()[pri:0, instance:com.edu.yanjie.LoginTest@27efef64]" name="loginFail" duration-ms="7017" started-at="2019-11-14T08:23:42Z" finished-at="2019-11-14T08:23:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.edu.yanjie.LoginTest.loginFail(LoginTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFail -->
        <test-method status="PASS" signature="loginSuccess()[pri:0, instance:com.edu.yanjie.LoginTest@27efef64]" name="loginSuccess" duration-ms="7109" started-at="2019-11-14T08:23:49Z" finished-at="2019-11-14T08:23:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSuccess -->
      </class> <!-- com.edu.yanjie.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
